In [ ]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

# Given data
x = np.array([1,0])

W1 = np.array([
    [0.2,0.3],
    [0.4,0.1]
])

W2 = np.array([
    [0.5],
    [0.6]
])

y = 1

# Forward propagation
hidden_input = np.dot(x,W1)
hidden_output = sigmoid(hidden_input)

output_input = np.dot(hidden_output,W2)
prediction = sigmoid(output_input)

loss = 0.5*(y-prediction)**2

print("Hidden Layer Output:")
print(hidden_output)

print("\nPrediction:")
print(prediction)

print("\nLoss:")
print(loss)

Hidden Layer Output:
[0.549834   0.57444252]

Prediction:
[0.65012359]

Loss:
[0.06120675]


In [ ]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Given values
x = np.array([[1, 0]])
y = np.array([[1]])

W1 = np.array([
    [0.2, 0.3],
    [0.4, 0.1]
])

W2 = np.array([
    [0.5],
    [0.6]
])

learning_rate = 0.1

# ---------- Forward Propagation ----------
hidden_input = np.dot(x, W1)
hidden_output = sigmoid(hidden_input)

output_input = np.dot(hidden_output, W2)
prediction = sigmoid(output_input)

loss = 0.5 * (y - prediction) ** 2

# ---------- Backpropagation ----------
delta_output = (prediction - y) * prediction * (1 - prediction)

dW2 = np.dot(hidden_output.T, delta_output)

delta_hidden = np.dot(delta_output, W2.T) * hidden_output * (1 - hidden_output)

dW1 = np.dot(x.T, delta_hidden)

# ---------- Weight Update ----------
W2_new = W2 - learning_rate * dW2
W1_new = W1 - learning_rate * dW1

# ---------- Results ----------
print("Hidden Output:")
print(hidden_output)

print("\nPrediction:")
print(prediction)

print("\nLoss:")
print(loss)

print("\nGradient W2")
print(dW2)

print("\nGradient W1")
print(dW1)

print("\nUpdated W2")
print(W2_new)

print("\nUpdated W1")
print(W1_new)

Hidden Output:
[[0.549834   0.57444252]]

Prediction:
[[0.65012359]]

Loss:
[[0.06120675]]

Gradient W2
[[-0.04375794]
 [-0.04571638]]

Gradient W1
[[-0.00984917 -0.01167297]
 [ 0.          0.        ]]

Updated W2
[[0.50437579]
 [0.60457164]]

Updated W1
[[0.20098492 0.3011673 ]
 [0.4        0.1       ]]
